services:

  db:
    image: postgres:16
    container_name: pet_postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pet_pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pet_backend
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - ../storage:/app/storage

  runner:
    build:
      context: ../runner
      dockerfile: Dockerfile
    image: portwatch-python-runner:1.0
    entrypoint: ["echo", "Runner image ready"]

  worker:
    build:
      context: ../runner_worker
    container_name: pet_worker
    env_file:
      - ../.env
    environment:
      HOST_STORAGE_PATH: ${HOST_STORAGE_PATH:-/host_mnt/c/Users/User/Desktop/PET_Projet/storage}
    depends_on:
      - db
      - runner
    volumes:
      - ../storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pet_pgdata: